name: where_the_food
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  dio: ^4.0.6
  logger: ^1.1.0
  pretty_dio_logger: ^1.1.1
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  keyboard_dismisser: ^2.0.1
  flutter_native_splash: ^2.1.6
  flutter_launcher_icons: ^0.9.2
  get_it: ^7.2.0
  get_storage: ^2.0.3
  pull_to_refresh: ^2.0.0
  flutter_easyloading: ^3.0.3
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  moor_flutter: ^4.1.0
  sqlite3_flutter_libs: ^0.5.5
  shimmer: ^2.0.0
  moor_generator: ^4.6.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  flutter_gen_runner:

flutter:

  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/svg/

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/png/logo_wtf.png"

flutter_native_splash:
  color: "#ffffff"
